local opt = vim.opt
opt.termguicolors=true
opt.syntax="enable"
opt.number=true
opt.relativenumber=true
opt.tabstop=4
--	opt.expandtab=true
opt.shiftwidth=4
opt.cursorline=true
opt.colorcolumn="80"
opt.ignorecase=true
opt.smartcase=true
opt.splitright=true
opt.splitbelow=true
opt.clipboard="unnamedplus"
opt.wildmenu=true
opt.hlsearch=false
